stages:
    preprocess_data:
          cmd:
              - python data/preprocess_save.py --config=params.yaml
          deps:
              - data/get_data.py
              - data/preprocess_save.py
              - data_given/winequality.csv         
          outs:
              - data/raw/winequality.csv
          
